# Notebook 1: Data Understanding & Preprocessing

This notebook focuses exclusively on:
- Loading the raw Telco churn dataset
- Exploring data structure and quality
- Cleaning and preprocessing the data
- Saving a clean dataset for modeling

## Step 1: Load Raw Dataset

The raw Telco customer churn dataset is loaded from an Excel file.

In [ ]:
import pandas as pd

df = pd.read_excel("../data/raw/Telco_customer_churn.xlsx")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [ ]:
df.shape

(7043, 33)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 1.8+ MB

## Step 2: Dataset Overview

This step examines:
- Number of rows and columns
- Data types
- Basic structure of the dataset

## Step 3: Missing Value Analysis

We identify columns with missing or inconsistent values that require cleaning.

In [ ]:
df.isna().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

Why we drop these 

IDs & location → no predictive value.    
Churn Score & CLTV → data leakage.     
Count → constant, useless.

## Step 4: Data Cleaning

In this step:
- `Total Charges` is converted to numeric
- Missing values are handled
- Irrelevant columns such as `Churn Reason` are removed

In [ ]:
df_clean = df.copy()

drop_cols = [
    "CustomerID",
    "Count",
    "Country",
    "State",
    "City",
    "Zip Code",
    "Lat Long",
    "Latitude",
    "Longitude",
    "Churn Score",
    "CLTV"
]

df_clean.drop(columns=drop_cols, inplace=True)
df_clean.shape

(7043, 22)

In [ ]:
df_clean["Total Charges"] = pd.to_numeric(
    df_clean["Total Charges"], errors="coerce"
)

df_clean["Total Charges"].isna().sum()

np.int64(11)

In [ ]:
df_clean["Total Charges"].fillna(
    df_clean["Total Charges"].median(), inplace=True
)

/var/folders/p7/_tj6dx057_1dhbry1wclql2w0000gp/T/ipykernel_21902/2201766858.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Total Charges"].fillna(

0        108.15
1        151.65
2        820.50
3       3046.05
4       5036.30
         ...
7038    1419.40
7039    1990.50
7040    7362.90
7041     346.45
7042    6844.50
Name: Total Charges, Length: 7043, dtype: float64

Pandas raised a copy-on-write warning due to chained assignment with inplace operations.
I resolved it by explicitly reassigning the column, which is the recommended and safer approach.

In [ ]:
df_clean["Total Charges"] = df_clean["Total Charges"].fillna(
    df_clean["Total Charges"].median()
)

In [ ]:
df_clean["Total Charges"].isna().sum()

np.int64(0)

In [ ]:
df_clean.drop(columns=["Churn Reason"], inplace=True)

In [ ]:
df_clean.shape

(7043, 21)

In [ ]:
df_clean.drop(columns=["Churn Label"], inplace=True)

In [ ]:
df_clean.shape

(7043, 20)

Churn Value is the numeric representation of churn and is suitable as a target variable for classification models, whereas Churn Label is redundant.

In [ ]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             7043 non-null   str
 1   Senior Citizen     7043 non-null   str
 2   Partner            7043 non-null   str
 3   Dependents         7043 non-null   str
 4   Tenure Months      7043 non-null   int64
 5   Phone Service      7043 non-null   str
 6   Multiple Lines     7043 non-null   str
 7   Internet Service   7043 non-null   str
 8   Online Security    7043 non-null   str
 9   Online Backup      7043 non-null   str
 10  Device Protection  7043 non-null   str
 11  Tech Support       7043 non-null   str
 12  Streaming TV       7043 non-null   str
 13  Streaming Movies   7043 non-null   str
 14  Contract           7043 non-null   str
 15  Paperless Billing  7043 non-null   str
 16  Payment Method     7043 non-null   str
 17  Monthly Charges    7043 non-null   float64
 18  Total Charges      7043 non-null   float64
 19  Churn Value        7043 non-null   int64
dtypes: float64(2), int64(2), str(16)
memory usage: 1.1 MB

In [ ]:
df_clean.isna().sum()

Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Value          0
dtype: int64

In [ ]:
df_clean.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1

## Step 5: Save Cleaned Dataset

The cleaned dataset is saved for use in the modeling notebook.

In [ ]:
df_clean.to_csv(
    "../data/processed/clean_telco_churn.csv",
    index=False
)